

name: My Shop Automation Framework Workflow

on:
  schedule:
  - cron: 30 23 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

        
    - name: Running Test Automation Framework with Maven
      run: mvn clean test -X -Dbrowser=chrome -DisLambdaTest=false -DisHeadless=true


    - name: Upload Test logs
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with: 
        name: Test logs
        path: logs/

    - name: Upload Extent Test Reports
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with: 
        name: Test Reports
        path: ExtentReports/extent_report.html

    - name: Test Execution Status
      run: echo "Test Execution Completed...  
        

        

      
















    
